// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txgfubqeodypgveuispo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4Z2Z1YnFlb2R5cGd2ZXVpc3BvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MjQyMTQsImV4cCI6MjA4OTUwMDIxNH0.7W0lbhFpq95XWSJzamaQ9JLMfxYQRvgtB6XA4y2IH7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});